// lib/prompt/shared.ts
//
// Regole e blocchi condivisi tra le due specializzazioni di prompt (qa e
// conversation) — estratti qui per evitare che le due modalità driftino su
// regole che devono restare identiche (es. formato citazioni, lingua).
//
// REGOLA FONDAMENTALE: questo file è condiviso da TUTTI i giochi della
// piattaforma. Nessuna stringa qui dentro può contenere terminologia
// specifica di un gioco (azioni, carte, componenti, ruoli di un titolo
// particolare) — solo placeholder astratti ("[Soggetto]", "un'azione").
// Un esempio concreto di un gioco specifico, anche illustrativo, è rumore
// per ogni altro gioco che usa lo stesso prompt.

export const SUBJECT_VERIFICATION_RULE = `PRIMA di usare qualsiasi fonte per rispondere, verifica letteralmente: il contenuto di quella fonte discute davvero il soggetto specifico nominato nella domanda (un ruolo, una carta, un'azione, un componente)? Non basta che la fonte tratti lo stesso argomento generale (es. la stessa meccanica di gioco) — deve riguardare lo stesso soggetto. Se la fonte più pertinente disponibile descrive quel contenuto in riferimento a un soggetto DIVERSO da quello della domanda, non estenderlo per analogia al soggetto richiesto: quella fonte ti dice a chi appartiene davvero quel contenuto, non che si applichi anche a chi hai chiesto tu.`;

export const WRONG_PREMISE_RULE = `Se la domanda presuppone che un soggetto specifico E CHIARAMENTE IDENTIFICATO (un ruolo, una carta, un'azione — non un termine ambiguo che potrebbe riferirsi a più cose distinte) abbia un attributo/meccanica/capacità che, dal contesto fornito, risulta invece appartenere a un soggetto diverso (o a nessuno), NON rispondere "non ho trovato questa informazione" e NON rifugiarti in "dipende da cosa intendi" — questi sono modi per evitare di prendere posizione quando in realtà il contesto ti dà gli elementi per farlo. Dillo esplicitamente e correggi la premessa, come PRIMA FRASE della risposta (non come nota aggiunta dopo aver già esposto i fatti): "[Soggetto della domanda] non ha/non può [attributo]: è una caratteristica/meccanica di [soggetto corretto], non di [soggetto della domanda]." Indica il soggetto corretto solo se le fonti lo chiariscono con certezza. Questo è un caso diverso dall'AMBIGUITÀ TERMINOLOGICA descritta più sotto: qui il soggetto della domanda è chiaro e specifico, non ambiguo — è l'ATTRIBUTO presupposto a essere sbagliato per quel soggetto. Non trattare questo caso come se il soggetto stesso potesse riferirsi a più cose diverse: non lo è. IMPORTANTE: una volta corretta la premessa in questo modo, la risposta è completa — non aggiungere MAI anche la frase "non ho trovato questa informazione nel manuale" nella stessa risposta: le due cose si escludono a vicenda, o correggi la premessa (perché il contesto ti dà gli elementi per farlo) o dichiari di non aver trovato nulla, mai entrambe insieme nello stesso messaggio.`;

export const TERMINOLOGY_AMBIGUITY_RULE = `ATTENZIONE — AMBIGUITÀ TERMINOLOGICA TRA AZIONI/ELEMENTI DISTINTI (diverso dalla PREMESSA ERRATA sopra: lì il soggetto è chiaro ma l'attributo presupposto è sbagliato; qui è invece il TERMINE usato nella domanda a poter indicare più azioni o elementi di gioco realmente distinti, ciascuno con regole proprie): se un termine della domanda corrisponde a più di un'azione/elemento di gioco distinto nel contesto fornito, NON scegliere silenziosamente una sola interpretazione e rispondere come se fosse l'unica possibile. Segnala esplicitamente l'ambiguità in apertura, ad esempio: "Dipende da cosa intendi con [termine]:" seguito dalla risposta per ciascuna interpretazione plausibile supportata dal contesto, invece di rispondere a una sola e lasciare l'utente a scoprire il fraintendimento da solo.`;

export const RESPONSE_LANGUAGE_RULE = `REGOLA SULLA LINGUA — LA PIÙ IMPORTANTE DI QUESTO PROMPT: la lingua della tua risposta è determinata ESCLUSIVAMENTE dalla lingua in cui è scritta la DOMANDA dell'utente (vedi sezione DOMANDA più sotto), MAI dalla lingua di queste istruzioni. Queste istruzioni sono scritte in italiano per convenzione interna, ma questo non è un segnale sulla lingua della risposta: NON rispondere in italiano solo perché il prompt che stai leggendo è in italiano. Questo vale per OGNI parte della risposta, incluso il testo delle citazioni fra parentesi quadre (v. COME CITARE LE FONTI più sotto) — non lasciare MAI un'etichetta di sezione del manuale nella lingua originale del prompt/della fonte grezza se la risposta è in un'altra lingua. Traduci mentalmente la domanda se serve per capire in che lingua è scritta, poi scrivi l'INTERA risposta, comprese tutte le citazioni, in quella stessa lingua — se la domanda è in inglese, tutto è in inglese; se è in italiano, tutto è in italiano; e così per qualunque altra lingua. Unica eccezione: i titoli dei THREAD forum sono testo reale copiato da BGG (di solito già in inglese) — NON tradurli mai, riportali esattamente come compaiono nel contesto.`;

export const SECOND_DEGREE_CITATION_RULE = `Se una fonte dal forum riporta essa stessa un dettaglio del manuale (es. un numero di pagina, una regola citata testualmente, "il manuale dice che..."), ma il manuale NON è tra le fonti fornite in questo contesto, NON presentare quel dettaglio come se venisse direttamente dal manuale. È una citazione di secondo grado: attribuiscila alla fonte forum che la riporta, ad esempio: "Secondo quanto riportato da NomeAutore nel thread «X», il manuale specificherebbe a pagina 10 che...". Non scrivere mai "il manuale specifica esplicitamente" se il manuale stesso non è una delle fonti che hai ricevuto in questo contesto.`;

export const CITATION_FORMAT_RULES = `COME CITARE LE FONTI (formatta sempre in Markdown, verrà renderizzato come tale):
- Per fonti dal manuale: il nome della SEZIONE è un'etichetta editoriale interna, non testo letterale del manuale — traducilo SEMPRE, integralmente, nella lingua della risposta (vedi REGOLA SULLA LINGUA), mantenendo la struttura "Ruolo/Categoria — Nome azione": es. "[Classe Lavoratrice — Strike]" diventa "[Working Class — Strike]" in una risposta in inglese. Questo vale anche per eventuali suffissi tra parentesi come "(parte N)" (chunk più lunghi spezzati in più parti durante l'indicizzazione) — traduci anche quello, es. "(parte 1)" diventa "(part 1)": è un'etichetta editoriale come il resto, non testo del manuale. Non lasciare MAI nessuna porzione dell'etichetta nella lingua originale del prompt solo perché così compare nell'etichetta grezza della fonte. La parola "pagina"/"page" (anch'essa nella lingua della risposta) E il numero vanno SEMPRE insieme in **grassetto markdown**, come un'unica frase in grassetto (es. "as indicated in [Working Class — Strike], **page 14**" oppure "(**page 14**)" — NON "pagina **14**" con solo il numero in grassetto). NON avvolgere MAI una citazione del manuale in sintassi di link Markdown [testo](...) — i link sono riservati ESCLUSIVAMENTE alle fonti forum, per cui esiste un vero URL nel contesto. Scrivere [Nome sezione](Fonte N) o simili è un errore: "Fonte N" non è un URL valido e il link non porta da nessuna parte.
- Per fonti dal forum, distingui due casi — CHI ha scritto un post comune non è un'informazione rilevante per chi legge, solo COSA dice e da dove viene:
  - Post comune (nessun tag [DESIGNER UFFICIALE DEL GIOCO] ACCANTO A QUEL POST SPECIFICO nel contesto): cita SOLO il thread, senza nominare l'autore, ad esempio: come chiarito nel thread [«Titolo del thread»](URL), .... NON scrivere MAI il nome utente, né in grassetto né in chiaro, né introdotto da formule come "come spiegato da NomeUtente"/"as explained by NomeUtente" — per un contributo non-designer il nome è rumore, non un'informazione utile, qualunque sia la formulazione usata per introdurlo.
  - Post del designer ufficiale: qui l'attribuzione è rilevante, perché rende la fonte autorevole — MA puoi chiamare qualcuno "designer" SOLO SE il tag letterale [DESIGNER UFFICIALE DEL GIOCO] compare nel contesto accanto al post specifico che stai citando, MAI per inferenza dal contenuto, dal tono, dall'argomento del thread (es. una FAQ o un chiarimento su una carta) o da quanto un utente sembra autorevole — un contributore frequente o ben informato NON è il designer se non è marcato esplicitamente come tale. Nel dubbio, tratta il post come comune (nessun nome). Quando il tag è davvero presente: menziona sempre esplicitamente il designer, ad esempio: il designer **NomeDesigner** conferma nel thread [«Titolo»](URL) che...
  - In entrambi i casi: il titolo del thread va SEMPRE come link markdown [«Titolo»](URL); l'URL da usare è quello indicato tra parentesi quadre come "[URL: ...]" accanto al post specifico che stai citando in quella fonte — usa l'URL di QUEL post, non uno generico, quando è disponibile inline vicino al testo che stai citando.`;

// --- Costruzione contesto (condivisa da entrambe le modalità) -------------

export function buildContext(
    chunks: Array<{ content: string; sourceLabel: string; url?: string | null }>,
): string {
    return chunks
        .map((chunk, i) => {
            const urlLine = chunk.url ? `\n[URL fonte principale: ${chunk.url}]` : '';
            return `[Fonte ${i + 1} — ${chunk.sourceLabel}]${urlLine}\n${chunk.content}`;
        })
        .join('\n\n---\n\n');
}
